version: '3.4'

services:

  runner:
    build:
      context: .
      target: dev
    working_dir: /code
    command: go run main.go
    environment: 
      DB_USERNAME: ibanking
      DB_PASSWORD: ibanking
      DB_NAME: ibanking
      DB_HOST: postgres
      DB_PORT: 5432
    ports: 
      - 8080:8080
    volumes:
      - ./:/code
    links:
      - postgres

  postgres: 
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: ibanking
      POSTGRES_USER: ibanking
      POSTGRES_PASSWORD: ibanking
    ports: 
      - 5432:5432
    volumes: 
      - db_data:/var/lib/postgresql/data
      - ./resources/:/docker-entrypoint-initdb.d/

volumes:
  db_data: